cask_args appdir: "/Applications"
brew "neomutt"
brew "dialog"
brew "offline-imap"
brew "notmuch"
brew "sqlite"
brew "kubectx", args: ["with-short-names"]
brew "kube-ps1"
brew "kubectl"
brew "z"
brew "urlview"
brew "contacts"
