# This viminfo file was generated by Vim 7.4.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Last Search Pattern:
~MSle0~/lf

# Command Line History (newest to oldest):
:/lf
:q
:q!
:GoInstallBinaries

# Search String History (newest to oldest):
? lf

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Input Line History (newest to oldest):

# Registers:
"a	CHAR	0
	

# File marks:
'0  1  0  ~/projects/src/github.com/tsuru/bs/Dockerfile
'1  35  0  ~/NERD_tree_1
'2  1  0  ~/NERD_tree_1
'3  1  0  ~/projects/src/github.com/tsuru/bs/main.go
'4  60  0  ~/projects/src/github.com/tsuru/bs/container/container.go
'5  111  0  ~/NERD_tree_1

# Jumplist (newest first):
-'  1  0  ~/projects/src/github.com/tsuru/bs/Dockerfile
-'  124  0  ~/projects/src/github.com/tsuru/bs/status/hostcheck.go
-'  52  3  ~/projects/src/github.com/tsuru/bs/container/container.go
-'  1  0  ~/projects/src/github.com/tsuru/bs/bslog/bslog.go
-'  99  0  ~/projects/src/github.com/tsuru/bs/config/config.go
-'  109  5  ~/projects/src/github.com/tsuru/bs/main.go
-'  1  0  ~/projects/src/github.com/tsuru/bs/main.go
-'  35  0  ~/NERD_tree_1
-'  47  0  ~/NERD_tree_1
-'  1  0  ~/NERD_tree_1
-'  52  0  ~/NERD_tree_1
-'  94  2  ~/NERD_tree_1
-'  60  0  ~/projects/src/github.com/tsuru/bs/container/container.go
-'  98  0  ~/NERD_tree_1
-'  110  2  ~/NERD_tree_1
-'  111  0  ~/NERD_tree_1
-'  119  0  ~/NERD_tree_1
-'  96  0  ~/NERD_tree_1
-'  104  0  ~/NERD_tree_1
-'  97  0  ~/NERD_tree_1
-'  105  0  ~/NERD_tree_1
-'  90  0  ~/NERD_tree_1
-'  66  2  ~/NERD_tree_1
-'  70  0  ~/NERD_tree_1
-'  82  2  ~/NERD_tree_1
-'  83  0  ~/NERD_tree_1
-'  91  0  ~/NERD_tree_1
-'  68  0  ~/NERD_tree_1
-'  76  0  ~/NERD_tree_1
-'  56  0  ~/NERD_tree_1
-'  69  0  ~/NERD_tree_1
-'  77  0  ~/NERD_tree_1
-'  54  0  ~/NERD_tree_1
-'  62  0  ~/NERD_tree_1
-'  84  2  ~/NERD_tree_1
-'  88  0  ~/NERD_tree_1
-'  100  2  ~/NERD_tree_1
-'  101  0  ~/NERD_tree_1
-'  109  0  ~/NERD_tree_1
-'  86  0  ~/NERD_tree_1
-'  87  0  ~/NERD_tree_1
-'  95  0  ~/NERD_tree_1
-'  80  0  ~/NERD_tree_1
-'  60  0  ~/NERD_tree_1
-'  72  2  ~/NERD_tree_1
-'  73  0  ~/NERD_tree_1
-'  81  0  ~/NERD_tree_1
-'  58  0  ~/NERD_tree_1
-'  59  0  ~/NERD_tree_1
-'  67  0  ~/NERD_tree_1
-'  11  0  ~/NERD_tree_1
-'  53  2  ~/NERD_tree_1
-'  57  0  ~/NERD_tree_1
-'  78  0  ~/NERD_tree_1
-'  55  0  ~/NERD_tree_1
-'  63  0  ~/NERD_tree_1
-'  64  0  ~/NERD_tree_1
-'  49  0  ~/NERD_tree_1
-'  25  2  ~/NERD_tree_1
-'  29  0  ~/NERD_tree_1
-'  41  2  ~/NERD_tree_1
-'  42  0  ~/NERD_tree_1
-'  50  0  ~/NERD_tree_1
-'  27  0  ~/NERD_tree_1
-'  35  0  ~/NERD_tree_1
-'  47  0  ~/NERD_tree_1
-'  1  0  ~/NERD_tree_1
-'  52  0  ~/NERD_tree_1
-'  94  2  ~/NERD_tree_1
-'  98  0  ~/NERD_tree_1
-'  110  2  ~/NERD_tree_1
-'  111  0  ~/NERD_tree_1
-'  119  0  ~/NERD_tree_1
-'  96  0  ~/NERD_tree_1
-'  104  0  ~/NERD_tree_1
-'  97  0  ~/NERD_tree_1
-'  105  0  ~/NERD_tree_1

# Buffer list:
%~/projects/src/github.com/tsuru/bs/main.go	109	5
%~/projects/src/github.com/tsuru/bs/config/config.go	99	0
%~/projects/src/github.com/tsuru/bs/bslog/bslog.go	1	0
%~/projects/src/github.com/tsuru/bs/container/container.go	52	3
%~/projects/src/github.com/tsuru/bs/status/hostcheck.go	124	0
%~/projects/src/github.com/tsuru/bs/Dockerfile	1	0

# History of marks within files (newest to oldest):

> ~/projects/src/github.com/tsuru/bs/main.go
	"	109	5

> ~/projects/src/github.com/tsuru/bs/NERD_tree_1
	"	12	0
	.	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0

> ~/projects/src/github.com/tsuru/bs/config/config.go
	"	99	0

> ~/projects/src/github.com/tsuru/bs/bslog/bslog.go
	"	1	0

> ~/projects/src/github.com/tsuru/bs/container/container.go
	"	52	3
	.	1	0
	+	1	0

> ~/projects/src/github.com/tsuru/bs/status/hostcheck.go
	"	124	0

> ~/projects/src/github.com/tsuru/bs/Dockerfile
	"	1	0

> ~/NERD_tree_1
	"	35	0
	.	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
