#!/bin/bash

bootstrap_fedora() {
  echo "Bootstrapping Fedora distribution"
  
  sudo cp ~/.yum-repos/* /etc/yum.repos.d/

  sudo dnf upgrade && sudo dnf update -y
  sudo dnf install snapd
  sudo ln -s /var/lib/snapd/snap /snap

  xargs --arg-file="/home/andrestc/dnf-software" sudo dnf -y install
  xargs --arg-file="/home/andrestc/snaps-software" sudo snap install

  sudo snap install skype --classic
  sudo snap install slack --classic
}

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

if [ "$system_type" = "Linux" ]; then

  mkdir -p /home/andrestc/bin/

  wget -O /home/andrestc/bin/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh
  wget -O /home/andrestc/bin/kube-ps1.sh https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
  wget -O /home/andrestc/bin/kctx https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
  wget -O /home/andrestc/bin/kns https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
  wget -O /home/andrestc/bin/minikube https://storage.googleapis.com/minikube/releases/v0.27.0/minikube-linux-amd64

  chmod +x /home/andrestc/bin/*

  if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
  fi

  echo "$OS - $VER"
  if [ "$OS" = "Fedora" ]; then
    bootstrap_fedora
  fi 

fi
